# Generated by Django 5.1.2 on 2024-10-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
    ]
